# Generated by Django 4.2 on 2023-05-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_conversation_speaker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='speaker_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.speaker'),
            preserve_default=False,
        ),
    ]
