# Generated by Django 4.2 on 2023-05-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_conversation_speaker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='speaker_id',
            new_name='speaker',
        ),
    ]
