# Generated by Django 4.2 on 2023-05-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_alter_speaker_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('remind', models.IntegerField(null=True)),
                ('repeat', models.IntegerField(null=True)),
                ('color', models.IntegerField(null=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
        ),
    ]
